apiVersion: dolphinscheduler.zncdata.dev/v1alpha1
kind: DolphinschedulerCluster
metadata:
  labels:
    app.kubernetes.io/name: dolphinschedulercluster
    app.kubernetes.io/instance: dolphinschedulercluster-sample
    app.kubernetes.io/part-of: dolphinscheduler-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: dolphinscheduler-operator
  name: dolphinschedulercluster-sample
spec:
  # TODO(user): Add fields here
